### ISSUE TITLE
trifecta-1.5.1 does not compile

### ISSUE THREAD

**Issue by peti** [ekmett/trifecta#41]
The error message is:

    src/Text/Trifecta/Highlight.hs:46:15:
        Ambiguous occurrence ‘Comment’
        It could refer to either ‘Text.Blaze.Internal.Comment’,
                                 imported from ‘Text.Blaze.Internal’ at src/Text/Trifecta/Highlight.hs:35:1-26
                              or ‘Text.Parser.Token.Highlight.Comment’,
                                 imported from ‘Text.Parser.Token.Highlight’ at src/Text/Trifecta/Highlight.hs:36:1-34

A complete build log is available at http://hydra.cryp.to/build/493580/nixlog/1/raw.

**Comment by david-christiansen** [comment]
This was fixed in https://github.com/ekmett/trifecta/pull/40 for me. Does the latest Git master work for you?

**Comment by peti** [comment]
Yes, the current `master` branch compiles fine (and passes its test suite).

**Comment by remdezx** [comment]
Can you push it to a hackage?

**Comment by robert-dodier** [comment]
I'm glad to hear the bug is fixed. I am trying to install Idris via cabal install idris and it is pulling in trifecta automatically as a dependency. How can I make use of the new version? Do I have to wait until a patched version is pushed out to whatever repository cabal is pulling packages from? If so, how do I know that a new version is available there? If I pull the current version from Git and build it myself, how do I convince cabal to use that version? Sorry for all the simplistic questions, I'm a n00b when it comes to Haskell. Thanks for your help, I appreciate it a lot.

**Comment by david-christiansen** [comment]
In the meantime, try using a version of Blaze that doesn't conflict with
Hackage Trifecta:

cabal install idris --constraint='blaze-markup <0.6.3'

**Comment by robert-dodier** [comment]
Thanks, that resolves the problem with trifecta for me.

**Comment by pthariensflame** [comment]
@robert-dodier For the record, you can install the current version of (nearly) any Haskell package by downloading the repo (Github has a convenient "Download as a zip file" button for just this kind of thing), `cd`ing to the resulting (unzipped) folder, and invoking `cabal install`.

**Comment by wdanilo** [comment]
This bug exist over a week now, can we push the fix to hackage?

**Comment by dysinger** [comment]
Also bit me ...

**Comment by dysinger** [comment]
Looks like it is also a bug for 1.5 

http://pastebin.com/7XBEJjJu

**Comment by acowley** [comment]
I, too, have been bitten.

**Comment by relrod** [comment]
As have I. :( @ekmett ping?

**Comment by nikita-volkov** [comment]
+1

**Comment by ekmett** [comment]
Shipped.

**Comment by david-christiansen** [comment]
Thank you very much @ekmett!

**Comment by pthariensflame** [comment]
Yay!
