### ISSUE TITLE
sliceIt misbehaves

### ISSUE THREAD

**Issue by nwf** [ekmett/trifecta#49]
Consider these two cases:

```
Prelude Text.Trifecta> starve (feed "e x" (feed "h" (stepParser (release mempty *>         some (notFollowedBy someSpace *> anyChar)  <* someSpace) mempty mempty)))
Success "he"

Prelude Text.Trifecta> starve (feed "e x" (feed "h" (stepParser (release mempty *> sliced (some (notFollowedBy someSpace *> anyChar)) <* someSpace) mempty mempty)))
Success ""
```

In particular, that parser really ought not be able to _accept_ the empty string, since it is just a combination of lookahead and "some anyChar".

That empty string is, in particular, the `mempty` passed to `wantIt` in `sliceIt`.  As might be expected, calling one more `feed` (with mempty, even) before calling `starve` causes the correct answer to emerge.

I am not smart enough to understand what `It` is doing, but this sure seems like a bug.

**Comment by ekmett** [comment]
Looks like a bug to me.

**Comment by fmthoma** [comment]
I think the problem is not in `It`, but in `stepParser`: The recursive case `go r (It ma k)` returns a continuation where `k` is called with the new rope, but `k` is never applied to the rope. Thus we always miss one step: A `StepCont` where there is already enough input present, but since the input is not fed to the continuation `k` of `It`, we wait for the next update (which may even be empty).

I think this bug can be solved by calling `simplifyIt` before pattern-matching on `It`:

```haskell
  go :: Rope -> It Rope (Stepping a) -> Step a
  go r m = case simplifyIt m r of
    (Pure (EO a _))     -> StepDone r a
    (Pure (EE e))       -> StepFail r $
                           let errDoc = explain (renderingCaret d0 bs0) e
                           in  ErrInfo errDoc (_finalDeltas e)
    (Pure (CO a _ _ _)) -> StepDone r a
    (Pure (CE d))       -> StepFail r d
    (It ma k)           -> StepCont r (case ma of
                                EO a _     -> Success a
                                EE e       -> Failure $
                                  ErrInfo (explain (renderingCaret d0 bs0) e) (d0 : _finalDeltas e)
                                CO a _ _ _ -> Success a
                                CE d       -> Failure d
                              ) (\s -> go s (k s))
```

This way, we perform the next step immediately.

When I say »I think«, that means I haven't tested anything except your examples, so I might be wrong.

**Comment by fmthoma** [comment]
BTW, the `stepParser` function has some more bugs (or unexpected behavior, so say the least). In particular, it allows to pass a ByteString `bs0` as an argument, which is ignored if the parser is reset first (`release mempty`), otherwise it interferes with additional input (via `feed`) in a very strange way.

Ideally, the `bs0` argument shouldn't be there, but that would be a breaking API change...

**Comment by nwf** [comment]
For whatever it's worth, I'd certainly be OK with a breaking change (and version bump) to fix these issues.

**Comment by fmthoma** [comment]
@nwf I'm working on a fix.

**Comment by ekmett** [comment]
I'm currently exploring removing the rope machinery entirely, which would remove 'It' from the equation entirely, but that said, it'd be nice to fix the current story before moving on.

**Comment by fmthoma** [comment]
Tested with the https://github.com/quchen/stgi test suite, which uses trifecta quite heavily. No regressions.

**Comment by quchen** [comment]
STGi doesn’t use a very complicated parser though; none of the fancy features of Trifecta are used, actually. It’s mostly just about parsing stuff until the semicolon and repeating that. A test yes, but not very thorough.
