### ISSUE TITLE
Documentation lacking for 'Delta'

### ISSUE THREAD

**Issue by expipiplus1** [ekmett/trifecta#60]
It would be nice to have explanations about what each constructor does, and each field in the constructors.

https://hackage.haskell.org/package/trifecta-1.5.2/docs/Text-Trifecta-Delta.html#t:Delta

**Comment by expipiplus1** [comment]
Ah, I see that the source has some documentation on the fields. It would be great if this could make it into the haddocks.

**Comment by lucques** [comment]
Hey, I'm struggling with getting the intuition for the Delta type. In particular, retrieving the current rendering via 'rend', I can obtain a Delta. I'm interested in the current line number and most of the times the Delta is of the Lines constructor, so that's fine. Sometimes though (and I don't see the pattern yet) the Delta is of the Columns constructor.

My question is: How is determined which constructor I get and how can I retrieve the line number anyway in the cases I get the Columns constructor?

Maybe you can give a short comment on this @ekmett or someone else familiar with it? Thank you very much in advance!

**Comment by lucques** [comment]
Thank you very much, I see now how the Directed constructor can be 
employed at the beginning. Cheers, Lukas

**Comment by quchen** [comment]
We’ve been working on documentation at HacFreiburg, see #73!

**Comment by ekmett** [comment]
Handled by #73.

**Comment by expipiplus1** [comment]
Thanks!
